version: "3.3"

services:
  puller:
    container_name: ethburnbot_puller
    image: ethburnbot:latest
    restart: always
    environment:
      ETHBURNBOT_ETHEREUM_RPC: ${ETHBURNBOT_ETHEREUM_RPC}
    command: python -m bin.run_puller
    volumes:
      - ./:/app

  tweeter:
    container_name: ethburnbot_tweeter
    image: ethburnbot:latest
    restart: always
    command: python -m bin.run_tweeter --dry-run
    volumes:
      - ./:/app
