version: "3.3"

services:
  puller:
    build:
      context: .
    container_name: ethburnbot_puller
    image: ethburnbot:latest
    restart: always
    environment:
      ETHBURNBOT_ETHEREUM_RPC: ${ETHBURNBOT_ETHEREUM_RPC}
    command: python -m bin.run_puller --block ${ETHBURNBOT_PULLER_BLOCK:-12965000}
    volumes:
      - ./:/app

  tweeter:
    build:
      context: .
    container_name: ethburnbot_tweeter
    image: ethburnbot:latest
    restart: always
    command: python -m bin.run_tweeter ${ETHBURNBOT_TWEETER_FLAGS}
    volumes:
      - ./:/app
