[tool.black]
exclude = '(data)'
line-length = 120

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 120
multi_line_output = 3
skip_glob = ["data/*"]
use_parentheses = true
